/*
* Common Purpose Library (http://github.com/ermig1979/Cpl).
*
* Copyright (c) 2021-2023 Yermalayeu Ihar,
*               2021-2022 Andrey Drogolyub,
*               2023-2023 Daniil Germanenko.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

#pragma once

#include "Cpl/Param.h"
#include "Cpl/Log.h"

namespace Cpl
{
    /*! @ingroup cpl_prop
    * \struct ParamProp
    * \brief Named property that stores a scalar of type T together with a description and optional range metadata.
    * \tparam T - Stored value type. Must support Cpl::%ToStr, Cpl::%ToVal and operator==.
    * \note Declare instances with CPL_PROP or CPL_PROP_EX. operator() returns a ParamValidator,
    *       so `field() = x` rejects values outside [Min(), Max()] and restores Default().
    *       ToVal and XML load write the parsed value directly and do not apply that range check.
    *       Inside a ParamStruct a property is saved to and loaded from a node of its own name.
    *       FullName() returns the name the property is registered under in its ParamStorage - the
    *       key of the map, which the property points at - and an empty string outside a storage.
    *       SaveBodyXml writes the descriptive body - "value", "desc", "value_min", "value_max"
    *       and "value_default"; LoadBodyXml reads the "value" child back, fails without it, and
    *       drops the rest.
    *       Only ParamStorage calls them, under a node of its own per property.
    *       The body leaves no text value empty: SaveBodyXml writes a single space instead, for an
    *       empty string as well as for "value_min" and "value_max" when Limited() is false. Inside
    *       a ParamStruct the value goes as it is, so an empty string becomes an empty node there.
    *       A string property that is empty or holds whitespace only does not survive a save and a
    *       load, in a storage and in a ParamStruct alike: the XML parser drops text made of
    *       whitespace only and ToVal of a String ignores an empty one, so the property keeps the
    *       value it had before the load.
    */
    template<class T> struct ParamProp: public Cpl::ParamLimited<T>
    {
        typedef T Type; //!< Stored value type.

        /*!
        * \fn String Description() const
        * \brief Returns a human-readable description of this property.
        * \return An empty string unless a derived class (typically generated by CPL_PROP or CPL_PROP_EX) overrides it.
        */
        virtual CPL_INLINE String Description() const
        {
            return String();
        }

        /*!
        * \fn bool Limited() const
        * \brief Checks whether this property publishes an explicit [Min(), Max()] range.
        * \return false unless a derived class (typically generated by CPL_PROP_EX) overrides it.
        * \note When false, XML save writes a single space for "value_min" and "value_max"
        *       instead of Min() and Max().
        */
        virtual CPL_INLINE bool Limited() const
        {
            return false;
        }

        /*!
        * \fn String ToStr() const
        * \brief Converts the stored value to a string.
        * \return Cpl::%ToStr of the stored value.
        */
        virtual CPL_INLINE String ToStr() const
        {
            return Cpl::ToStr<T>(this->_value);
        }

        /*!
        * \fn String FullName() const
        * \brief Returns the dotted name "group.prop" of this property inside its ParamStorage.
        * \return A copy of the name this property is registered under in the map of the storage,
        *         or an empty string when the property does not belong to a ParamStorage.
        * \note The name is returned by value because the key it is taken from belongs to the map
        *       of the storage: that map dies with the storage and is destroyed before the
        *       properties are, so a reference into it would outlive what it points at.
        */
        CPL_INLINE String FullName() const
        {
            return _fullName ? *_fullName : String();
        }

        /*!
        * \fn void ToVal(const String & str)
        * \brief Parses a string into the stored value.
        * \param [in] str - Text recognized by Cpl::%ToVal for type T.
        * \note Writes directly to the stored value. Unlike operator(), this does not
        *       reject out-of-range values or restore Default().
        */
        virtual CPL_INLINE void ToVal(const String & str)
        {
            return Cpl::ToVal<T>(str, this->_value);
        }

        // The full name belongs to the place a property occupies in a storage, not to its value, so
        // a copy never takes it from the source: it would point into a storage that does not hold
        // the copy. An assignment keeps the full name this property already has, while the node
        // name is assigned by Param along with the value. A property is not movable, see the note
        // of Param, so a move request copies.
        ParamProp(const ParamProp& other)
            : Base(other)
            , _fullName(NULL)
        {
        }

        ParamProp& operator = (const ParamProp& other)
        {
            Base::operator = (other);
            return *this;
        }

    protected:
        typedef Cpl::ParamLimited<T> Base;
        typedef Cpl::Param<int> Unknown;

        // The name of a property is the key it has in the map of its storage, so the property
        // keeps the address of that key instead of a copy of the string. Keys of std::map do not
        // move, and BuildMap points every property at the key of its own storage.
        const String* _fullName;

        ParamProp(const String& name)
            : Base(name)
            , _fullName(NULL)
        {
        }

        // A property is the only kind of node ParamStorage may reach through ParamProp<int>*,
        // see the note of Param::IsProp.
        bool IsProp() const override
        {
            return true;
        }

        // ParamStorage keeps every property as ParamProp<int>*, whatever the stored type is, and
        // the offset of _fullName depends on that type, so the field is reached through a virtual
        // method only.
        virtual CPL_INLINE void SetFullName(const String* fullName)
        {
            _fullName = fullName;
        }

        // The field above lies after the ParamValue part, whose End() would leave the walk over the
        // properties of a group inside it.
        Unknown* End() const override
        {
            return (Unknown*)(this + 1);
        }

        // ParamLimited loads through the validator, which replaces a value outside [Min(), Max()]
        // with the default one. A property takes the value of the file as it is, the way the class
        // promises and the way LoadBodyXml does it for ParamStorage.
        bool LoadNodeXml(Xml::XmlNode<char>* xmlParent) override
        {
            return Cpl::ParamValue<T>::LoadNodeXml(xmlParent);
        }

        // The body of a property is its item in the map of a storage, so a body without a value is
        // a broken item and fails the load, the way an item without a body does.
        virtual bool LoadBodyXml(Xml::XmlNode<char>* xmlParent)
        {
            Xml::XmlNode<char>* xmlValue = xmlParent->FirstNode("value");
            if (!xmlValue)
                return false;
            Cpl::ToVal(xmlValue->Value(), this->_value);
            return true;
        }

        static CPL_INLINE const char * NotEmpty(const String& value)
        {
            return value.empty() ? " " : value.c_str();
        }

        virtual void SaveBodyXml(Xml::XmlDocument<char>& xmlDoc, Xml::XmlNode<char>* xmlParent) const
        {
            Xml::XmlNode<char>* xmlValue = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("value"));
            xmlValue->Value(xmlDoc.AllocateString(NotEmpty(Cpl::ToStr(this->_value))));
            xmlParent->AppendNode(xmlValue);

            Xml::XmlNode<char>* xmlDescr = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("desc"));
            xmlDescr->Value(xmlDoc.AllocateString(NotEmpty(this->Description())));
            xmlParent->AppendNode(xmlDescr);

            Xml::XmlNode<char>* xmlMin = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("value_min"));
            xmlMin->Value(xmlDoc.AllocateString(this->Limited() ? NotEmpty(Cpl::ToStr(this->Min())) : " "));
            xmlParent->AppendNode(xmlMin);

            Xml::XmlNode<char>* xmlMax = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("value_max"));
            xmlMax->Value(xmlDoc.AllocateString(this->Limited() ? NotEmpty(Cpl::ToStr(this->Max())) : " "));
            xmlParent->AppendNode(xmlMax);

            Xml::XmlNode<char>* xmlDefault = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("value_default"));
            xmlDefault->Value(xmlDoc.AllocateString(NotEmpty(Cpl::ToStr(this->Default()))));
            xmlParent->AppendNode(xmlDefault);
        }

        template<typename> friend struct ParamStorage;
    };

    //---------------------------------------------------------------------------------------------

    /*! @ingroup cpl_prop
    * \struct ParamStorage
    * \brief Root parameter that indexes nested property groups by dotted names of the form "group.prop".
    * \tparam T - User struct whose members are property groups declared with CPL_PROP_GROUP.
    *             Each group is a struct of CPL_PROP / CPL_PROP_EX fields.
    * \note Declare a holder with CPL_PROP_STORAGE. operator() returns T.
    *       The constructor walks two levels of children (groups, then properties), fills an
    *       internal map used by SetProperty and GetProperty and gives every property the dotted
    *       name it is registered under, which ParamProp::FullName() returns.
    *       A storage holds groups only and a group holds properties only: a child of another kind
    *       is skipped with an Error in the log and stays out of the map, so SetProperty and
    *       GetProperty do not know its name and the XML of the storage, written and read through
    *       that map, neither saves nor loads it.
    *       A storage inside a storage is such a child too, it is reported and skipped; the nested
    *       one keeps its own map and serves its properties through its own SetProperty and GetProperty.
    *       In XML a structure may hold one storage only: whatever its name, a storage writes under
    *       a node named "storage" and loads from the first such node of its parent, so storages of
    *       one structure take the values of each other: a second storage loads the node of the
    *       first one, and after a short save, which leaves out a storage that has not changed, the
    *       first storage loads the node of the second one. The load reports success in both cases.
    *       YAML has no map: a storage is saved and loaded there as a plain structure, every child
    *       by its own node name, so a skipped child goes to YAML.
    *       The map lies after the ParamStruct part, so End() is overridden: an enclosing structure
    *       steps over the whole storage, while the own children stop at ChildEnd().
    *       A copy rebuilds that map from its own fields, so every storage owns an independent set
    *       of properties; an assignment keeps its own map, because it writes the children of T in
    *       place and leaves their addresses unchanged, and a property keeps the name of its own
    *       storage, because ParamProp never assigns that name from the source. A storage is not
    *       movable: a move request binds to the copy and leaves the source untouched.
    *       XML save writes a "storage" / "map" tree: a "count" child and one "item" per
    *       property (or per Changed() property when full is false). Each item has
    *       "first" (the dotted name) and "second" (the ParamProp XML).
    *       XML load skips unknown names after a Debug log. An absent "storage" node inside a
    *       structure leaves the storage as it is and is not a failure; at the top of a file it
    *       fails the load, as does a missing "map", "first" or "second" node, or a "second"
    *       without "value". YAML loads a storage as a plain structure, so there a file without
    *       its node loads with success at the top as well.
    */
    template<class T> struct ParamStorage : public Cpl::ParamStruct<T>
    {
        typedef T Type; //!< Stored configuration type.

        /*!
        * \fn bool SetProperty(const String& name, const String& value)
        * \brief Sets the property named name from a string.
        * \param [in] name - Dotted name "group.prop" built from the group and field identifiers.
        * \param [in] value - Text passed to ParamProp::ToVal. Not range-checked.
        * \return true if name was found and updated, false if name is unknown.
        */
        bool SetProperty(const String& name, const String& value)
        {
            Map::iterator it = _map.find(name);
            if (it == _map.end())
                return false;
            it->second->ToVal(value);
            return true;
        }

        /*!
        * \fn bool GetProperty(const String& name, String& value) const
        * \brief Reads the property named name as a string.
        * \param [in] name - Dotted name "group.prop" built from the group and field identifiers.
        * \param [out] value - Receives ParamProp::ToStr of the stored value when name is found.
        * \return true if name was found, false if name is unknown. value is left unchanged on failure.
        */
        bool GetProperty(const String& name, String& value) const
        {
            Map::const_iterator it = _map.find(name);
            if (it == _map.end())
                return false;
            value = it->second->ToStr();
            return true;
        }

        // _map points at the property subobjects of this very object, so a copy builds its own map
        // instead of taking the pointers of the source. An assignment keeps the map it has: the
        // base assigns the children in place, so their addresses do not change. A storage is not
        // movable, see the note of Param, so a move request copies.
        ParamStorage(const ParamStorage& other)
            : Base(other)
        {
            BuildMap();
        }

        ParamStorage& operator = (const ParamStorage& other)
        {
            Base::operator = (other);
            return *this;
        }

    protected:
        typedef Cpl::ParamStruct<T> Base;
        typedef Cpl::Param<int> Unknown;
        typedef Cpl::ParamProp<int> UnknownProp;
        typedef Cpl::ParamStruct<int> UnknownGroup;
        typedef std::map<String, UnknownProp*> Map;

        Map _map;

        ParamStorage(const String& name)
            : Base(name)
        {
            BuildMap();
        }

        // The map lies after the ParamStruct part, so the end inherited from it would leave a
        // storage used as a field of another structure overlapping the field declared after it.
        Unknown* End() const override
        {
            return (Unknown*)(this + 1);
        }

        // A storage is a structure, but not a group: its children are groups, not properties, so
        // the walk of an enclosing storage must report the storage itself instead of reporting
        // every group inside it. Nesting a storage in a storage is not supported.
        bool IsStruct() const override
        {
            return false;
        }

        bool LoadNodeXml(Xml::XmlNode<char>* xmlParent) override
        {
            // Inside a structure an absent node is not a failure: a short save leaves out a storage
            // that has not changed. At the top of a file the node is always written, so a file
            // without it is not a file of a storage.
            Xml::XmlNode<char>* xmlStorage = xmlParent->FirstNode("storage");
            if (xmlStorage == NULL)
                return xmlParent->Type() != Xml::NodeDocument;
            Xml::XmlNode<char>* xmlMap = xmlStorage->FirstNode("map");
            if (xmlMap == NULL)
                return false;
            for (Xml::XmlNode<char>* xmlItem = xmlMap->FirstNode("item"); xmlItem; xmlItem = xmlItem->NextSibling())
            {
                Xml::XmlNode<char>* xmlFirst = xmlItem->FirstNode("first");
                if (xmlFirst == NULL)
                    return false;
                Map::iterator it = _map.find(xmlFirst->Value());
                if (it == _map.end())
                {
                    CPL_LOG_SS(Debug, "Load XML has unknown propery '" << xmlFirst->Value() << "'!")
                    continue;
                }
                Xml::XmlNode<char>* xmlSecond = xmlItem->FirstNode("second");
                if (xmlSecond == NULL)
                    return false;
                if (!it->second->LoadBodyXml(xmlSecond))
                    return false;
            }
            return true;
        }

        void SaveNodeXml(Xml::XmlDocument<char>& xmlDoc, Xml::XmlNode<char>* xmlParent, bool full) const override
        {
            Xml::XmlNode<char>* xmlStorage = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("storage"));
            Xml::XmlNode<char>* xmlMap = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("map"));

            Xml::XmlNode<char>* xmlCount = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("count"));
            if(full)
                xmlCount->Value(xmlDoc.AllocateString(Cpl::ToStr(_map.size()).c_str()));
            else
            {
                size_t count = 0;
                for (Map::const_iterator it = _map.begin(); it != _map.end(); ++it)
                    if (it->second->Changed())
                        count++;
                xmlCount->Value(xmlDoc.AllocateString(Cpl::ToStr(count).c_str()));
            }
            xmlMap->AppendNode(xmlCount);

            for (Map::const_iterator it = _map.begin(); it != _map.end(); ++it)
            {
                if (it->second->Changed() || full)
                {
                    Xml::XmlNode<char>* xmlItem = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("item"));

                    Xml::XmlNode<char>* xmlFirst = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("first"));
                    xmlFirst->Value(xmlDoc.AllocateString(it->first.c_str()));
                    xmlItem->AppendNode(xmlFirst);

                    Xml::XmlNode<char>* xmlSecond = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("second"));
                    it->second->SaveBodyXml(xmlDoc, xmlSecond);
                    xmlItem->AppendNode(xmlSecond);

                    xmlMap->AppendNode(xmlItem);
                }
            }
            xmlStorage->AppendNode(xmlMap);
            xmlParent->AppendNode(xmlStorage);
        }

    private:
        void BuildMap()
        {
            for (Unknown* group = this->ChildBeg(); group < this->ChildEnd(); group = group->End())
            {
                // A child that is not a group holds no properties and answers the question below
                // with a method of its own, which sends the walk into memory that holds no node.
                if (!group->IsStruct())
                {
                    CPL_LOG_SS(Error, "The child '" << group->Name() << "' of the storage '" << this->Name()
                        << "' is not a group! It is skipped, declare it with CPL_PROP_GROUP.");
                    continue;
                }

                // The properties of a group end where its ParamStruct part does: End() of the
                // group lies past the fields the group itself may add.
                UnknownGroup* groupNode = (UnknownGroup*)group;
                for (Unknown* prop = groupNode->ChildBeg(); prop < groupNode->ChildEnd(); prop = prop->End())
                {
                    // Every pointer of the map is used as a property, so a child of another kind
                    // has no place in it and the virtual call below would land in a slot such a
                    // node fills with a method of its own.
                    if (!prop->IsProp())
                    {
                        CPL_LOG_SS(Error, "The child '" << prop->Name() << "' of the group '" << group->Name()
                            << "' is not a property! It is skipped, declare it with CPL_PROP or CPL_PROP_EX.");
                        continue;
                    }

                    String name = group->Name() + "." + prop->Name();
                    UnknownProp* property = (UnknownProp*)prop;
                    _map[name] = property;
                    property->SetFullName(&_map.find(name)->first);
                }
            }
        }
    };
}

//-------------------------------------------------------------------------------------------------

/*! @ingroup cpl_prop
* \def CPL_PROP(type, name, value, descr)
* \brief Declares a named property field with a default value and a description.
* \param type - Stored value type. Must support Cpl::%ToStr, Cpl::%ToVal and operator==.
* \param name - Field name. Used as the member identifier and as the second half of the dotted map key.
* \param value - Default value. Changed() is true when the stored value differs from this default.
* \param descr - Description string returned by Description().
* \note Limited() stays false, so XML "value_min" and "value_max" are a single space.
*       Assignment through operator() still uses ParamLimited range checks against
*       std::numeric_limits<type>::min() and max().
*/
#define CPL_PROP(type, name, value, descr) \
struct Param_##name : public Cpl::ParamProp<type> \
{ \
    typedef Cpl::ParamProp<type> Base; \
    Param_##name() : Base(#name) { this->_value = this->Default(); } \
    type Default() const override { return value; } \
    Cpl::String Description() const override { return descr; } \
} name;

/*! @ingroup cpl_prop
* \def CPL_PROP_EX(type, name, value, min, max, descr)
* \brief Declares a named property field with a default, an inclusive [min, max] range and a description.
* \param type - Stored value type. Must be comparable with operator<=.
* \param name - Field name. Used as the member identifier and as the second half of the dotted map key.
* \param value - Default value. Must satisfy min <= value <= max (asserted in the constructor).
* \param min - Inclusive lower bound written to XML "value_min".
* \param max - Inclusive upper bound written to XML "value_max".
* \param descr - Description string returned by Description().
* \note Limited() is true. operator() rejects assignments outside [min, max] and restores value.
*       ToVal and XML load still write the parsed value without that check.
*/
#define CPL_PROP_EX(type, name, value, min, max, descr) \
struct Param_##name : public Cpl::ParamProp<type> \
{ \
    typedef Cpl::ParamProp<type> Base; \
    Param_##name() : Base(#name) { assert((min) <= (value) && (value) <= (max)); this->_value = this->Default(); } \
    type Default() const override { return value; } \
    type Min() const override { return min; } \
    type Max() const override { return max; } \
    Cpl::String Description() const override { return descr; } \
    bool Limited() const override { return true; } \
} name;

/*! @ingroup cpl_prop
* \def CPL_PROP_GROUP(type, name)
* \brief Declares a nested property-group field. Equivalent to CPL_PARAM_STRUCT(type, name).
* \param type - User struct whose members are properties declared with CPL_PROP or CPL_PROP_EX.
* \param name - Field name. Used as the member identifier and as the first half of the dotted map key.
*/
#define CPL_PROP_GROUP(type, name) CPL_PARAM_STRUCT(type, name)

/*! @ingroup cpl_prop
* \def CPL_PROP_STORAGE(storage, type, name)
* \brief Declares a named ParamStorage holder for a configuration struct of property groups.
* \param storage - Name of the generated holder type.
* \param type - User struct whose members are groups declared with CPL_PROP_GROUP.
* \param name - Root node name passed to the ParamStorage constructor.
* \note The holder is default-constructible. operator() returns type. Use SetProperty and
*       GetProperty with dotted names "group.prop". Save and Load use the ParamStorage XML format.
*/
#define CPL_PROP_STORAGE(storage, type, name) \
struct storage : public Cpl::ParamStorage<type> \
{ \
    typedef Cpl::ParamStorage<type> Base; \
    storage() : Base(#name) {} \
};
