/*
* Common Purpose Library (http://github.com/ermig1979/Cpl).
*
* Copyright (c) 2021-2023 Yermalayeu Ihar,
*               2021-2022 Andrey Drogolyub,
*               2023-2023 Daniil Germanenko.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

#pragma once

#include "Cpl/Param.h"
#include "Cpl/Log.h"

namespace Cpl
{
    /*! @ingroup cpl_prop
    * \struct ParamProp
    * \brief Named property that stores a scalar of type T together with a description and optional range metadata.
    * \tparam T - Stored value type. Must support Cpl::%ToStr, Cpl::%ToVal and operator==.
    * \note Declare instances with CPL_PROP or CPL_PROP_EX. operator() returns a ParamValidator,
    *       so `field() = x` rejects values outside [Min(), Max()] and restores Default().
    *       ToVal and XML load write the parsed value directly and do not apply that range check.
    *       XML save writes children "value", "desc", "value_min", "value_max" and "value_default".
    *       When Limited() is false, "value_min" and "value_max" are a single space.
    *       Empty strings are written as a single space. XML load reads only the "value" child.
    */
    template<class T> struct ParamProp: public Cpl::ParamLimited<T>
    {
        typedef T Type; //!< Stored value type.

        /*!
        * \fn String Description() const
        * \brief Returns a human-readable description of this property.
        * \return An empty string unless a derived class (typically generated by CPL_PROP or CPL_PROP_EX) overrides it.
        */
        virtual CPL_INLINE String Description() const
        {
            return String();
        }

        /*!
        * \fn bool Limited() const
        * \brief Checks whether this property publishes an explicit [Min(), Max()] range.
        * \return false unless a derived class (typically generated by CPL_PROP_EX) overrides it.
        * \note When false, XML save writes a single space for "value_min" and "value_max"
        *       instead of Min() and Max().
        */
        virtual CPL_INLINE bool Limited() const
        {
            return false;
        }

        /*!
        * \fn String ToStr() const
        * \brief Converts the stored value to a string.
        * \return Cpl::%ToStr of the stored value.
        */
        virtual CPL_INLINE String ToStr() const
        {
            return Cpl::ToStr<T>(this->_value);
        }

        /*!
        * \fn void ToVal(const String & str)
        * \brief Parses a string into the stored value.
        * \param [in] str - Text recognized by Cpl::%ToVal for type T.
        * \note Writes directly to the stored value. Unlike operator(), this does not
        *       reject out-of-range values or restore Default().
        */
        virtual CPL_INLINE void ToVal(const String & str)
        {
            return Cpl::ToVal<T>(str, this->_value);
        }

    protected:
        typedef Cpl::ParamLimited<T> Base;
        typedef Cpl::Param<int> Unknown;

        ParamProp(const String& name)
            : Base(name)
        {
        }

        bool LoadNodeXml(Xml::XmlNode<char>* xmlParent) override
        {
            Xml::XmlNode<char>* xmlValue = xmlParent->FirstNode("value");
            if(xmlValue)
                Cpl::ToVal(xmlValue->Value(), this->_value);
            return true;
        }

        static CPL_INLINE const char * NotEmpty(const String& value)
        {
            return value.empty() ? " " : value.c_str();
        }

        void SaveNodeXml(Xml::XmlDocument<char>& xmlDoc, Xml::XmlNode<char>* xmlParent, bool full) const override
        {
            Xml::XmlNode<char>* xmlValue = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("value"));
            xmlValue->Value(xmlDoc.AllocateString(NotEmpty(Cpl::ToStr(this->_value))));
            xmlParent->AppendNode(xmlValue);

            Xml::XmlNode<char>* xmlDescr = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("desc"));
            xmlDescr->Value(xmlDoc.AllocateString(NotEmpty(this->Description())));
            xmlParent->AppendNode(xmlDescr);

            Xml::XmlNode<char>* xmlMin = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("value_min"));
            xmlMin->Value(xmlDoc.AllocateString(this->Limited() ? NotEmpty(Cpl::ToStr(this->Min())) : " "));
            xmlParent->AppendNode(xmlMin);

            Xml::XmlNode<char>* xmlMax = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("value_max"));
            xmlMax->Value(xmlDoc.AllocateString(this->Limited() ? NotEmpty(Cpl::ToStr(this->Max())) : " "));
            xmlParent->AppendNode(xmlMax);

            Xml::XmlNode<char>* xmlDefault = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("value_default"));
            xmlDefault->Value(xmlDoc.AllocateString(NotEmpty(Cpl::ToStr(this->Default()))));
            xmlParent->AppendNode(xmlDefault);
        }

        template<typename> friend struct ParamStorage;
    };

    //---------------------------------------------------------------------------------------------

    /*! @ingroup cpl_prop
    * \struct ParamStorage
    * \brief Root parameter that indexes nested property groups by dotted names of the form "group.prop".
    * \tparam T - User struct whose members are property groups declared with CPL_PROP_GROUP.
    *             Each group is a struct of CPL_PROP / CPL_PROP_EX fields.
    * \note Declare a holder with CPL_PROP_STORAGE. operator() returns T.
    *       The constructor walks two levels of children (groups, then properties) and
    *       fills an internal map used by SetProperty and GetProperty.
    *       XML save writes a "storage" / "map" tree: a "count" child and one "item" per
    *       property (or per Changed() property when full is false). Each item has
    *       "first" (the dotted name) and "second" (the ParamProp XML).
    *       XML load skips unknown names after a Debug log; a missing "storage", "map",
    *       "first" or "second" node fails the load.
    */
    template<class T> struct ParamStorage : public Cpl::ParamStruct<T>
    {
        typedef T Type; //!< Stored configuration type.

        /*!
        * \fn bool SetProperty(const String& name, const String& value)
        * \brief Sets the property named name from a string.
        * \param [in] name - Dotted name "group.prop" built from the group and field identifiers.
        * \param [in] value - Text passed to ParamProp::ToVal. Not range-checked.
        * \return true if name was found and updated, false if name is unknown.
        */
        bool SetProperty(const String& name, const String& value)
        {
            Map::iterator it = _map.find(name);
            if (it == _map.end())
                return false;
            it->second->ToVal(value);
            return true;
        }

        /*!
        * \fn bool GetProperty(const String& name, String& value) const
        * \brief Reads the property named name as a string.
        * \param [in] name - Dotted name "group.prop" built from the group and field identifiers.
        * \param [out] value - Receives ParamProp::ToStr of the stored value when name is found.
        * \return true if name was found, false if name is unknown. value is left unchanged on failure.
        */
        bool GetProperty(const String& name, String& value) const
        {
            Map::const_iterator it = _map.find(name);
            if (it == _map.end())
                return false;
            value = it->second->ToStr();
            return true;
        }

    protected:
        typedef Cpl::ParamStruct<T> Base;
        typedef Cpl::Param<int> Unknown;
        typedef Cpl::ParamProp<int> UnknownProp;
        typedef Cpl::ParamStruct<int> UnknownGroup;
        typedef std::map<String, UnknownProp*> Map;

        Map _map;

        ParamStorage(const String& name)
            : Base(name)
        {
            for (Unknown* group = this->ChildBeg(); group < this->End(); group = group->End())
            {
                for (Unknown* prop = ((UnknownGroup*)group)->ChildBeg(); prop < group->End(); prop = prop->End())
                {
                    String name = group->Name() + "." + prop->Name();
                    _map[name] = (UnknownProp*)prop;
                }
            }
        }

        bool LoadNodeXml(Xml::XmlNode<char>* xmlParent) override
        {
            Xml::XmlNode<char>* xmlStorage = xmlParent->FirstNode("storage");
            if (xmlStorage == NULL)
                return false;
            Xml::XmlNode<char>* xmlMap = xmlStorage->FirstNode("map");
            if (xmlMap == NULL)
                return false;
            for (Xml::XmlNode<char>* xmlItem = xmlMap->FirstNode("item"); xmlItem; xmlItem = xmlItem->NextSibling())
            {
                Xml::XmlNode<char>* xmlFirst = xmlItem->FirstNode("first");
                if (xmlFirst == NULL)
                    return false;
                Map::iterator it = _map.find(xmlFirst->Value());
                if (it == _map.end())
                {
                    CPL_LOG_SS(Debug, "Load XML has unknown propery '" << xmlFirst->Value() << "'!")
                    continue;
                }
                Xml::XmlNode<char>* xmlSecond = xmlItem->FirstNode("second");
                if (xmlSecond == NULL)
                    return false;
                if (!it->second->LoadNodeXml(xmlSecond))
                    return false;
            }
            return true;
        }

        void SaveNodeXml(Xml::XmlDocument<char>& xmlDoc, Xml::XmlNode<char>* xmlParent, bool full) const override
        {
            Xml::XmlNode<char>* xmlStorage = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("storage"));
            Xml::XmlNode<char>* xmlMap = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("map"));

            Xml::XmlNode<char>* xmlCount = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("count"));
            if(full)
                xmlCount->Value(xmlDoc.AllocateString(Cpl::ToStr(_map.size()).c_str()));
            else
            {
                size_t count = 0;
                for (Map::const_iterator it = _map.begin(); it != _map.end(); ++it)
                    if (it->second->Changed())
                        count++;
                xmlCount->Value(xmlDoc.AllocateString(Cpl::ToStr(count).c_str()));
            }
            xmlMap->AppendNode(xmlCount);

            for (Map::const_iterator it = _map.begin(); it != _map.end(); ++it)
            {
                if (it->second->Changed() || full)
                {
                    Xml::XmlNode<char>* xmlItem = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("item"));

                    Xml::XmlNode<char>* xmlFirst = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("first"));
                    xmlFirst->Value(xmlDoc.AllocateString(it->first.c_str()));
                    xmlItem->AppendNode(xmlFirst);

                    Xml::XmlNode<char>* xmlSecond = xmlDoc.AllocateNode(Xml::NodeElement, xmlDoc.AllocateString("second"));
                    it->second->SaveNodeXml(xmlDoc, xmlSecond, true);
                    xmlItem->AppendNode(xmlSecond);

                    xmlMap->AppendNode(xmlItem);
                }
            }
            xmlStorage->AppendNode(xmlMap);
            xmlParent->AppendNode(xmlStorage);
        }
    };
}

//-------------------------------------------------------------------------------------------------

/*! @ingroup cpl_prop
* \def CPL_PROP(type, name, value, descr)
* \brief Declares a named property field with a default value and a description.
* \param type - Stored value type. Must support Cpl::%ToStr, Cpl::%ToVal and operator==.
* \param name - Field name. Used as the member identifier and as the second half of the dotted map key.
* \param value - Default value. Changed() is true when the stored value differs from this default.
* \param descr - Description string returned by Description().
* \note Limited() stays false, so XML "value_min" and "value_max" are a single space.
*       Assignment through operator() still uses ParamLimited range checks against
*       std::numeric_limits<type>::min() and max().
*/
#define CPL_PROP(type, name, value, descr) \
struct Param_##name : public Cpl::ParamProp<type> \
{ \
    typedef Cpl::ParamProp<type> Base; \
    Param_##name() : Base(#name) { this->_value = this->Default(); } \
    type Default() const override { return value; } \
    Cpl::String Description() const override { return descr; } \
} name;

/*! @ingroup cpl_prop
* \def CPL_PROP_EX(type, name, value, min, max, descr)
* \brief Declares a named property field with a default, an inclusive [min, max] range and a description.
* \param type - Stored value type. Must be comparable with operator<=.
* \param name - Field name. Used as the member identifier and as the second half of the dotted map key.
* \param value - Default value. Must satisfy min <= value <= max (asserted in the constructor).
* \param min - Inclusive lower bound written to XML "value_min".
* \param max - Inclusive upper bound written to XML "value_max".
* \param descr - Description string returned by Description().
* \note Limited() is true. operator() rejects assignments outside [min, max] and restores value.
*       ToVal and XML load still write the parsed value without that check.
*/
#define CPL_PROP_EX(type, name, value, min, max, descr) \
struct Param_##name : public Cpl::ParamProp<type> \
{ \
    typedef Cpl::ParamProp<type> Base; \
    Param_##name() : Base(#name) { assert(min <= value && value <= max); this->_value = this->Default(); } \
    type Default() const override { return value; } \
    type Min() const override { return min; } \
    type Max() const override { return max; } \
    Cpl::String Description() const override { return descr; } \
    bool Limited() const override { return true; } \
} name;

/*! @ingroup cpl_prop
* \def CPL_PROP_GROUP(type, name)
* \brief Declares a nested property-group field. Equivalent to CPL_PARAM_STRUCT(type, name).
* \param type - User struct whose members are properties declared with CPL_PROP or CPL_PROP_EX.
* \param name - Field name. Used as the member identifier and as the first half of the dotted map key.
*/
#define CPL_PROP_GROUP(type, name) CPL_PARAM_STRUCT(type, name)

/*! @ingroup cpl_prop
* \def CPL_PROP_STORAGE(storage, type, name)
* \brief Declares a named ParamStorage holder for a configuration struct of property groups.
* \param storage - Name of the generated holder type.
* \param type - User struct whose members are groups declared with CPL_PROP_GROUP.
* \param name - Root node name passed to the ParamStorage constructor.
* \note The holder is default-constructible. operator() returns type. Use SetProperty and
*       GetProperty with dotted names "group.prop". Save and Load use the ParamStorage XML format.
*/
#define CPL_PROP_STORAGE(storage, type, name) \
struct storage : public Cpl::ParamStorage<type> \
{ \
    typedef Cpl::ParamStorage<type> Base; \
    storage() : Base(#name) {} \
};
